# This is a basic workflow to help you get started with Actions

name: build

# Controls when the action will run.
on:
  schedule:
    - cron: "0 7 * * *" # monthly
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: write
env:
  ZIG_VERSION: "0.15.2"
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  prepare_env:
    name: Prepare build version
    runs-on: ubuntu-latest
    env:
      EMACS_REPO: https://github.com/akiyosi/zonvie.git
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - name: Get build version
        id: vars
        run: |
          mkdir -p ./git/zonvie
          cd ./git/zonvie/
          git clone -b main --depth 1 $EMACS_REPO .
          ts=`date +'%Y%m%d'`
          commit=`git rev-parse --short=7 HEAD`
          major_ver=0
          version=`echo ${major_ver}.${{ github.run_number }}.${ts}.${commit}`

          echo "commit=${commit}" >> $GITHUB_ENV
          echo "version=${version}" >> $GITHUB_ENV
          echo "pkg_version=${major_ver}.${{ github.run_number }}.0.0" >> $GITHUB_ENV
    outputs:
      repo: ${{ env.EMACS_REPO }}
      version: ${{ env.version }}
      pkg_version: ${{ env.pkg_version }}
      commit: ${{ env.commit }}

  build:
    needs: prepare_env
    name: Build zonvie
    # Matrix strategy from
    # https://github.com/msys2/MINGW-packages/blob/master/.github/workflows/main.yml
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: x64
            target: x86_64-windows-gnu
    env:
      EMACS_REPO: ${{ needs.prepare_env.outputs.repo }}
      EMACS_PKG_VERSION: ${{ needs.prepare_env.outputs.pkg_version }}
      EMACS_CERT_SECRET: ${{ secrets.EMACS_CERT_SECRET }}

    # The type of runner that the job will run on


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      - name: Setup Zig
        uses: mlugg/setup-zig@v2
        with:
          version: ${{ env.ZIG_VERSION }}

      - name: Clone zonvie
        run: |
          # echo "clone zonvie"
          mkdir -p ./git/zonvie
          cd ./git/zonvie/
          git clone --filter=tree:0 --no-checkout $EMACS_REPO .
          git checkout ${{ needs.prepare_env.outputs.commit }}
          echo `pwd`

      - name: Build Windows App (Release)
        run: |
          echo `pwd`
          cd ./git/zonvie/
          zig build windows -Dtarget=${{ matrix.target }} -Doptimize=ReleaseFast

      - name: Create Windows ZIP
        run: |
          cd ./git/zonvie/
          ZIP_NAME="zonvie-${{ github.ref_name }}-windows-${{ matrix.arch }}.zip"
          cd windows/zig-out
          zip -r "../../$ZIP_NAME" zonvie.exe
          cd ../..
          echo `ls`
          echo `pwd`
      # Upload release for each build
      - name: Upload binaries to release
        id: upload_release
        uses: svenstaro/upload-release-action@v2
        run: |
          cd ./git/zonvie/
          cho `ls`
          echo `pwd`
        with:
          repo_token: ${{ github.token }}
          file: ./*{.zip}
          # file_glob: true
          tag: v${{ needs.prepare_env.outputs.version }}
          release_name: zonvie_${{ needs.prepare_env.outputs.version }}
          draft: false
          prerelease: false
